on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        default: "stg"
        options:
          - stg
          - prd
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set AWS Access Keys for passed environment
        run: |
          if [ "${{ inputs.environment }}" == "stg" ]; then
              echo "AWS_ACCESS_KEY_ID=stg" >> $GITHUB_ENV
          elif [ "${{ inputs.environment }}" == "prd" ]; then 
              echo "AWS_ACCESS_KEY_ID=prd" >> $GITHUB_ENV
          fi

      - name: Print ENV
        run: echo $AWS_ACCESS_KEY_ID
